### ISSUE TITLE
AIHelpSDK for iOS simulator

### ISSUE THREAD

**Issue by ngtrungt** [AI-HELP/sdk-ios-example#12]
Device: Macbook Pro M1
Mac OS: 12.5.1
Xcode: 13.4.1

Dear team,
Currently, I can run it on the iOS device but on the iOS simulator, it does not work.
Here is the error message: 
Pods/AIHelpSDK/AIHelpSDK/AIHelpSupportSDK.framework/AIHelpSupportSDK(SVGLineElement.o), building for iOS Simulator, but linking in object file built for iOS, file '/Pods/AIHelpSDK/AIHelpSDK/AIHelpSupportSDK.framework/AIHelpSupportSDK' for architecture arm64

Do you guys consider making a version for the simulator?

Thanks and regards,

**Comment by Joeljt** [comment]
Hi, I think the problem is not with the simulator, but with the apple chip macbook.

As M1 no longer supports x86_64 architecture, the AIHelpSDK.framework may get this error while compling on M1 devices.

You can try to remove the x86_64 architecture from AIHelpSDK with `lipo -remove [architecture] [location] -o [output_location]` CLI. You could get more infomation at [here](https://stackoverflow.com/questions/36349071/how-to-remove-unwanted-architecture-x86-64-from-xcode-build).

If you still have further issues, please contact us at [our office site](https://aihelp.net/) or via [support@aihelp.net](mailto:support@aihelp.net).

**Comment by trungnv5** [comment]
Hi @Joeljt ,
I'm still encountering the same problem after removing the x86_64 architecture.
